version: "3"
services:
  server:
    build: server/

    command: ./server
    ports:
      - 9090:9090

  client:
    depends_on:
      - server
    build: client/

    command: ./client
    network_mode: host

    stdin_open: true
    tty: true

